import type { PrefijoCatalogo } from "./schema";

export const ARGENTINA_PREFIJOS_CATALOGO: PrefijoCatalogo[] = [
  { prefijo: "11", areaLocal: "AMBA" },
  { prefijo: "220", areaLocal: "MERLO (PROV. BUENOS AIRES)" },
  { prefijo: "221", areaLocal: "LA PLATA - BUENOS AIRES" },
  { prefijo: "223", areaLocal: "MAR DEL PLATA - BUENOS AIRES" },
  { prefijo: "230", areaLocal: "PILAR (PROV. BUENOS AIRES)" },
  { prefijo: "236", areaLocal: "JUNIN (PROV. BUENOS AIRES)" },
  { prefijo: "237", areaLocal: "MORENO - BUENOS AIRES" },
  { prefijo: "249", areaLocal: "TANDIL - BUENOS AIRES" },
  { prefijo: "260", areaLocal: "SAN RAFAEL (PROV. MENDOZA)" },
  { prefijo: "261", areaLocal: "MENDOZA" },
  { prefijo: "263", areaLocal: "SAN MARTIN (PROV. MENDOZA)" },
  { prefijo: "264", areaLocal: "SAN JUAN" },
  { prefijo: "266", areaLocal: "SAN LUIS (PROV. SAN LUIS)" },
  { prefijo: "280", areaLocal: "TRELEW - CHUBUT" },
  { prefijo: "291", areaLocal: "BAHIA BLANCA - BUENOS AIRES" },
  { prefijo: "294", areaLocal: "SAN CARLOS DE BARILOCHE - RIO NEGRO" },
  { prefijo: "297", areaLocal: "COMODORO RIVADAVIA - CHUBUT" },
  { prefijo: "298", areaLocal: "GENERAL ROCA (PROV. RIO NEGRO)" },
  { prefijo: "299", areaLocal: "NEUQUEN" },
  { prefijo: "336", areaLocal: "SAN NICOLAS - BUENOS AIRES" },
  { prefijo: "341", areaLocal: "ROSARIO - SANTA FE" },
  { prefijo: "342", areaLocal: "SANTA FE" },
  { prefijo: "343", areaLocal: "PARANA - ENTRE RIOS" },
  { prefijo: "345", areaLocal: "CONCORDIA - ENTRE RIOS" },
  { prefijo: "348", areaLocal: "ESCOBAR - BUENOS AIRES" },
  { prefijo: "351", areaLocal: "CORDOBA" },
  { prefijo: "353", areaLocal: "VILLA MARIA - CORDOBA" },
  { prefijo: "358", areaLocal: "RIO CUARTO - CORDOBA" },
  { prefijo: "362", areaLocal: "RESISTENCIA - CHACO" },
  { prefijo: "364", areaLocal: "PRESIDENCIA ROQUE SAENZ PENA - CHACO" },
  { prefijo: "370", areaLocal: "FORMOSA" },
  { prefijo: "376", areaLocal: "POSADAS - MISIONES" },
  { prefijo: "379", areaLocal: "CORRIENTES" },
  { prefijo: "380", areaLocal: "LA RIOJA" },
  { prefijo: "381", areaLocal: "SAN MIGUEL DE TUCUMAN" },
  { prefijo: "383", areaLocal: "CATAMARCA" },
  { prefijo: "385", areaLocal: "SANTIAGO DEL ESTERO" },
  { prefijo: "387", areaLocal: "SALTA" },
  { prefijo: "388", areaLocal: "SAN SALVADOR DE JUJUY" },
  { prefijo: "2202", areaLocal: "GONZALEZ CATAN - BUENOS AIRES" },
  { prefijo: "2221", areaLocal: "MAGDALENA - BUENOS AIRES" },
  { prefijo: "2223", areaLocal: "CORONEL BRANDSEN - BUENOS AIRES" },
  { prefijo: "2224", areaLocal: "GLEW - BUENOS AIRES" },
  { prefijo: "2225", areaLocal: "ALEJANDRO KORN - BUENOS AIRES" },
  { prefijo: "2226", areaLocal: "CANUELAS - BUENOS AIRES" },
  { prefijo: "2227", areaLocal: "LOBOS - BUENOS AIRES" },
  { prefijo: "2229", areaLocal: "JUAN MARIA GUTIERREZ - BUENOS AIRES" },
  { prefijo: "2241", areaLocal: "CHASCOMUS - BUENOS AIRES" },
  { prefijo: "2242", areaLocal: "LEZAMA - BUENOS AIRES" },
  { prefijo: "2243", areaLocal: "GENERAL BELGRANO - BUENOS AIRES" },
  { prefijo: "2244", areaLocal: "LAS FLORES (PROV. BUENOS AIRES)" },
  { prefijo: "2245", areaLocal: "DOLORES (PROV. BUENOS AIRES)" },
  { prefijo: "2246", areaLocal: "SANTA TERESITA - BUENOS AIRES" },
  { prefijo: "2252", areaLocal: "SAN CLEMENTE DEL TUYU - BUENOS AIRES" },
  { prefijo: "2254", areaLocal: "PINAMAR - BUENOS AIRES" },
  { prefijo: "2255", areaLocal: "VILLA GESELL - BUENOS AIRES" },
  { prefijo: "2257", areaLocal: "MAR DE AJO - BUENOS AIRES" },
  { prefijo: "2261", areaLocal: "LOBERIA - BUENOS AIRES" },
  { prefijo: "2262", areaLocal: "NECOCHEA - BUENOS AIRES" },
  { prefijo: "2264", areaLocal: "LA DULCE - BUENOS AIRES" },
  { prefijo: "2265", areaLocal: "CORONEL VIDAL - BUENOS AIRES" },
  { prefijo: "2266", areaLocal: "BALCARCE - BUENOS AIRES" },
  { prefijo: "2267", areaLocal: "GENERAL MADARIAGA - BUENOS AIRES" },
  { prefijo: "2268", areaLocal: "MAIPU (PROV. BUENOS AIRES)" },
  { prefijo: "2271", areaLocal: "MONTE - BUENOS AIRES" },
  { prefijo: "2272", areaLocal: "NAVARRO - BUENOS AIRES" },
  { prefijo: "2273", areaLocal: "CARMEN DE ARECO - BUENOS AIRES" },
  { prefijo: "2274", areaLocal: "CARLOS SPEGAZZINI - BUENOS AIRES" },
  { prefijo: "2281", areaLocal: "AZUL - BUENOS AIRES" },
  { prefijo: "2283", areaLocal: "TAPALQUE - BUENOS AIRES" },
  { prefijo: "2284", areaLocal: "OLAVARRIA - BUENOS AIRES" },
  { prefijo: "2285", areaLocal: "LAPRIDA - BUENOS AIRES" },
  { prefijo: "2286", areaLocal: "GENERAL LAMADRID - BUENOS AIRES" },
  { prefijo: "2291", areaLocal: "MIRAMAR (PROV. BUENOS AIRES)" },
  { prefijo: "2292", areaLocal: "BENITO JUAREZ - BUENOS AIRES" },
  { prefijo: "2296", areaLocal: "AYACUCHO - BUENOS AIRES" },
  { prefijo: "2297", areaLocal: "RAUCH - BUENOS AIRES" },
  { prefijo: "2302", areaLocal: "GENERAL PICO - LA PAMPA" },
  { prefijo: "2314", areaLocal: "BOLIVAR - BUENOS AIRES" },
  { prefijo: "2316", areaLocal: "DAIREAUX - BUENOS AIRES" },
  { prefijo: "2317", areaLocal: "9 DE JULIO (PROV. BUENOS AIRES)" },
  { prefijo: "2320", areaLocal: "JOSE C. PAZ - BUENOS AIRES" },
  { prefijo: "2323", areaLocal: "LUJAN (PROV. BUENOS AIRES)" },
  { prefijo: "2324", areaLocal: "MERCEDES (PROV. BUENOS AIRES)" },
  { prefijo: "2325", areaLocal: "SAN ANDRES DE GILES - BUENOS AIRES" },
  { prefijo: "2326", areaLocal: "SAN ANTONIO DE ARECO - BUENOS AIRES" },
  { prefijo: "2331", areaLocal: "REALICO - LA PAMPA" },
  { prefijo: "2333", areaLocal: "QUEMU QUEMU - LA PAMPA" },
  { prefijo: "2334", areaLocal: "EDUARDO CASTEX - LA PAMPA" },
  { prefijo: "2335", areaLocal: "CALEUFU - LA PAMPA" },
  { prefijo: "2336", areaLocal: "HUINCA RENANCO - CORDOBA" },
  { prefijo: "2337", areaLocal: "AMERICA - BUENOS AIRES" },
  { prefijo: "2338", areaLocal: "VICTORICA - LA PAMPA" },
  { prefijo: "2342", areaLocal: "BRAGADO - BUENOS AIRES" },
  { prefijo: "2343", areaLocal: "NORBERTO DE LA RIESTRA - BUENOS AIRES" },
  { prefijo: "2344", areaLocal: "SALADILLO (PROV. BUENOS AIRES)" },
  { prefijo: "2345", areaLocal: "25 DE MAYO (PROV. BUENOS AIRES)" },
  { prefijo: "2346", areaLocal: "CHIVILCOY - BUENOS AIRES" },
  { prefijo: "2352", areaLocal: "CHACABUCO - BUENOS AIRES" },
  { prefijo: "2353", areaLocal: "GENERAL ARENALES - BUENOS AIRES" },
  { prefijo: "2354", areaLocal: "VEDIA - BUENOS AIRES" },
  { prefijo: "2355", areaLocal: "LINCOLN - BUENOS AIRES" },
  { prefijo: "2356", areaLocal: "GENERAL PINTO - BUENOS AIRES" },
  { prefijo: "2357", areaLocal: "CARLOS TEJEDOR - BUENOS AIRES" },
  { prefijo: "2358", areaLocal: "LOS TOLDOS (PROV. BUENOS AIRES)" },
  { prefijo: "2392", areaLocal: "TRENQUE LAUQUEN - BUENOS AIRES" },
  { prefijo: "2393", areaLocal: "SALAZAR - BUENOS AIRES" },
  { prefijo: "2394", areaLocal: "TRES LOMAS - BUENOS AIRES" },
  { prefijo: "2395", areaLocal: "CARLOS CASARES - BUENOS AIRES" },
  { prefijo: "2396", areaLocal: "PEHUAJO - BUENOS AIRES" },
  { prefijo: "2473", areaLocal: "COLON (PROV. BUENOS AIRES)" },
  { prefijo: "2474", areaLocal: "SALTO - BUENOS AIRES" },
  { prefijo: "2475", areaLocal: "ROJAS - BUENOS AIRES" },
  { prefijo: "2477", areaLocal: "PERGAMINO - BUENOS AIRES" },
  { prefijo: "2478", areaLocal: "ARRECIFES - BUENOS AIRES" },
  { prefijo: "2622", areaLocal: "TUNUYAN - MENDOZA" },
  { prefijo: "2624", areaLocal: "USPALLATA - MENDOZA" },
  { prefijo: "2625", areaLocal: "GENERAL ALVEAR (PROV. MENDOZA)" },
  { prefijo: "2626", areaLocal: "LA PAZ (PROV. MENDOZA)" },
  { prefijo: "2646", areaLocal: "SAN AGUSTIN DEL VALLE FERTIL - SAN JUAN" },
  { prefijo: "2647", areaLocal: "JACHAL - SAN JUAN" },
  { prefijo: "2648", areaLocal: "CALINGASTA - SAN JUAN" },
  { prefijo: "2651", areaLocal: "SAN FRANCISCO DEL MONTE DE ORO - SAN LUIS" },
  { prefijo: "2655", areaLocal: "LA TOMA - SAN LUIS" },
  { prefijo: "2656", areaLocal: "TILISARAO - SAN LUIS" },
  { prefijo: "2657", areaLocal: "MERCEDES (PROV. SAN LUIS)" },
  { prefijo: "2658", areaLocal: "BUENA ESPERANZA - SAN LUIS" },
  { prefijo: "2901", areaLocal: "USHUAIA - TIERRA DEL FUEGO" },
  { prefijo: "2902", areaLocal: "RIO TURBIO - SANTA CRUZ" },
  { prefijo: "2903", areaLocal: "RIO MAYO - CHUBUT" },
  { prefijo: "2920", areaLocal: "VIEDMA - RIO NEGRO" },
  { prefijo: "2921", areaLocal: "CORONEL DORREGO - BUENOS AIRES" },
  { prefijo: "2922", areaLocal: "CORONEL PRINGLES - BUENOS AIRES" },
  { prefijo: "2923", areaLocal: "PIGUE - BUENOS AIRES" },
  { prefijo: "2924", areaLocal: "DARREGUEIRA - BUENOS AIRES" },
  { prefijo: "2925", areaLocal: "VILLA IRIS - BUENOS AIRES" },
  { prefijo: "2926", areaLocal: "CORONEL SUAREZ - BUENOS AIRES" },
  { prefijo: "2927", areaLocal: "MEDANOS (PROV. BUENOS AIRES)" },
  { prefijo: "2928", areaLocal: "PEDRO LURO - BUENOS AIRES" },
  { prefijo: "2929", areaLocal: "GUAMINI - BUENOS AIRES" },
  { prefijo: "2931", areaLocal: "RIO COLORADO (PROV. RIO NEGRO)" },
  { prefijo: "2932", areaLocal: "PUNTA ALTA - BUENOS AIRES" },
  { prefijo: "2933", areaLocal: "HUANGUELEN SUR - BUENOS AIRES" },
  { prefijo: "2934", areaLocal: "SAN ANTONIO OESTE - RIO NEGRO" },
  { prefijo: "2935", areaLocal: "RIVERA - BUENOS AIRES" },
  { prefijo: "2936", areaLocal: "CARHUE - BUENOS AIRES" },
  { prefijo: "2940", areaLocal: "INGENIERO JACOBACCI - RIO NEGRO" },
  { prefijo: "2942", areaLocal: "ZAPALA - NEUQUEN" },
  { prefijo: "2945", areaLocal: "ESQUEL - CHUBUT" },
  { prefijo: "2946", areaLocal: "CHOELE CHOEL - RIO NEGRO" },
  { prefijo: "2948", areaLocal: "CHOS MALAL - NEUQUEN" },
  { prefijo: "2952", areaLocal: "GENERAL ACHA - LA PAMPA" },
  { prefijo: "2953", areaLocal: "MACACHIN - LA PAMPA" },
  { prefijo: "2954", areaLocal: "SANTA ROSA (PROV. LA PAMPA)" },
  { prefijo: "2962", areaLocal: "SAN JULIAN - SANTA CRUZ" },
  { prefijo: "2963", areaLocal: "PERITO MORENO - SANTA CRUZ" },
  { prefijo: "2964", areaLocal: "RIO GRANDE (PROV. TIERRA DEL FUEGO)" },
  { prefijo: "2966", areaLocal: "RIO GALLEGOS - SANTA CRUZ" },
  { prefijo: "2972", areaLocal: "SAN MARTIN DE LOS ANDES - NEUQUEN" },
  { prefijo: "2982", areaLocal: "ORENSE - BUENOS AIRES" },
  { prefijo: "2983", areaLocal: "TRES ARROYOS - BUENOS AIRES" },
  { prefijo: "3327", areaLocal: "LOPEZ CAMELO - BUENOS AIRES" },
  { prefijo: "3329", areaLocal: "SAN PEDRO (PROV. BUENOS AIRES)" },
  { prefijo: "3382", areaLocal: "RUFINO - SANTA FE" },
  { prefijo: "3385", areaLocal: "LABOULAYE - CORDOBA" },
  { prefijo: "3387", areaLocal: "BOUCHARD - CORDOBA" },
  { prefijo: "3388", areaLocal: "GENERAL VILLEGAS - BUENOS AIRES" },
  { prefijo: "3400", areaLocal: "VILLA CONSTITUCION - SANTA FE" },
  { prefijo: "3401", areaLocal: "EL TREBOL - SANTA FE" },
  { prefijo: "3402", areaLocal: "ARROYO SECO - SANTA FE" },
  { prefijo: "3404", areaLocal: "SAN CARLOS CENTRO - SANTA FE" },
  { prefijo: "3405", areaLocal: "SAN JAVIER (PROV. SANTA FE)" },
  { prefijo: "3406", areaLocal: "SAN JORGE (PROV. SANTA FE)" },
  { prefijo: "3407", areaLocal: "RAMALLO - BUENOS AIRES" },
  { prefijo: "3408", areaLocal: "SAN CRISTOBAL - SANTA FE" },
  { prefijo: "3409", areaLocal: "MOISES VILLE - SANTA FE" },
  { prefijo: "3435", areaLocal: "NOGOYA - ENTRE RIOS" },
  { prefijo: "3436", areaLocal: "VICTORIA - ENTRE RIOS" },
  { prefijo: "3437", areaLocal: "LA PAZ (PROV. ENTRE RIOS)" },
  { prefijo: "3438", areaLocal: "BOVRIL - ENTRE RIOS" },
  { prefijo: "3442", areaLocal: "CONCEPCION DEL URUGUAY - ENTRE RIOS" },
  { prefijo: "3444", areaLocal: "GUALEGUAY - ENTRE RIOS" },
  { prefijo: "3445", areaLocal: "ROSARIO DEL TALA - ENTRE RIOS" },
  { prefijo: "3446", areaLocal: "GUALEGUAYCHU - ENTRE RIOS" },
  { prefijo: "3447", areaLocal: "COLON (PROV. ENTRE RIOS)" },
  { prefijo: "3454", areaLocal: "FEDERAL - ENTRE RIOS" },
  { prefijo: "3455", areaLocal: "VILLAGUAY - ENTRE RIOS" },
  { prefijo: "3456", areaLocal: "CHAJARI - ENTRE RIOS" },
  { prefijo: "3458", areaLocal: "SAN JOSE DE FELICIANO - ENTRE RIOS" },
  { prefijo: "3460", areaLocal: "SANTA TERESA (PROV. SANTA FE)" },
  { prefijo: "3462", areaLocal: "VENADO TUERTO - SANTA FE" },
  { prefijo: "3463", areaLocal: "CANALS - CORDOBA" },
  { prefijo: "3464", areaLocal: "CASILDA - SANTA FE" },
  { prefijo: "3465", areaLocal: "FIRMAT - SANTA FE" },
  { prefijo: "3466", areaLocal: "BARRANCAS (PROV. SANTA FE)" },
  { prefijo: "3467", areaLocal: "CRUZ ALTA - CORDOBA" },
  { prefijo: "3468", areaLocal: "CORRAL DE BUSTOS - CORDOBA" },
  { prefijo: "3469", areaLocal: "ACEBAL - SANTA FE" },
  { prefijo: "3471", areaLocal: "CANADA DE GOMEZ - SANTA FE" },
  { prefijo: "3472", areaLocal: "MARCOS JUAREZ - CORDOBA" },
  { prefijo: "3476", areaLocal: "SAN LORENZO (PROV. SANTA FE)" },
  { prefijo: "3482", areaLocal: "RECONQUISTA - SANTA FE" },
  { prefijo: "3483", areaLocal: "VERA - SANTA FE" },
  { prefijo: "3487", areaLocal: "ZARATE - BUENOS AIRES" },
  { prefijo: "3489", areaLocal: "CAMPANA - BUENOS AIRES" },
  { prefijo: "3491", areaLocal: "CERES - SANTA FE" },
  { prefijo: "3492", areaLocal: "RAFAELA - SANTA FE" },
  { prefijo: "3493", areaLocal: "SUNCHALES - SANTA FE" },
  { prefijo: "3496", areaLocal: "ESPERANZA (PROV. SANTA FE)" },
  { prefijo: "3497", areaLocal: "LLAMBI CAMPBELL - SANTA FE" },
  { prefijo: "3498", areaLocal: "SAN JUSTO (PROV. SANTA FE)" },
  { prefijo: "3521", areaLocal: "DEAN FUNES - CORDOBA" },
  { prefijo: "3522", areaLocal: "VILLA DE MARIA DE RIO SECO - CORDOBA" },
  { prefijo: "3524", areaLocal: "VILLA DEL TOTORAL - CORDOBA" },
  { prefijo: "3525", areaLocal: "JESUS MARIA - CORDOBA" },
  { prefijo: "3532", areaLocal: "OLIVA - CORDOBA" },
  { prefijo: "3533", areaLocal: "LAS VARILLAS - CORDOBA" },
  { prefijo: "3537", areaLocal: "BELL VILLE - CORDOBA" },
  { prefijo: "3541", areaLocal: "VILLA CARLOS PAZ - CORDOBA" },
  { prefijo: "3542", areaLocal: "SALSACATE - CORDOBA" },
  { prefijo: "3543", areaLocal: "ARGUELLO - CORDOBA" },
  { prefijo: "3544", areaLocal: "VILLA DOLORES - CORDOBA" },
  { prefijo: "3546", areaLocal: "SANTA ROSA DE CALAMUCHITA - CORDOBA" },
  { prefijo: "3547", areaLocal: "ALTA GRACIA - CORDOBA" },
  { prefijo: "3548", areaLocal: "LA FALDA - CORDOBA" },
  { prefijo: "3549", areaLocal: "CRUZ DEL EJE - CORDOBA" },
  { prefijo: "3562", areaLocal: "MORTEROS - CORDOBA" },
  { prefijo: "3563", areaLocal: "BALNEARIA - CORDOBA" },
  { prefijo: "3564", areaLocal: "SAN FRANCISCO (PROV. CORDOBA)" },
  { prefijo: "3571", areaLocal: "RIO TERCERO - CORDOBA" },
  { prefijo: "3572", areaLocal: "RIO SEGUNDO - CORDOBA" },
  { prefijo: "3573", areaLocal: "VILLA DEL ROSARIO (PROV. CORDOBA)" },
  { prefijo: "3574", areaLocal: "RIO PRIMERO - CORDOBA" },
  { prefijo: "3575", areaLocal: "LA PUERTA (PROV. CORDOBA)" },
  { prefijo: "3576", areaLocal: "ARROYITO (PROV. CORDOBA)" },
  { prefijo: "3582", areaLocal: "SAMPACHO - CORDOBA" },
  { prefijo: "3583", areaLocal: "VICUNA MACKENNA - CORDOBA" },
  { prefijo: "3584", areaLocal: "LA CARLOTA - CORDOBA" },
  { prefijo: "3585", areaLocal: "ADELIA MARIA - CORDOBA" },
  { prefijo: "3711", areaLocal: "INGENIERO GUILLERMO N. JUAREZ - FORMOSA" },
  { prefijo: "3715", areaLocal: "LAS LOMITAS - FORMOSA" },
  { prefijo: "3716", areaLocal: "IBARRETA - FORMOSA" },
  { prefijo: "3718", areaLocal: "CLORINDA - FORMOSA" },
  { prefijo: "3721", areaLocal: "CHARADAI - CHACO" },
  { prefijo: "3725", areaLocal: "GENERAL JOSE DE SAN MARTIN - CHACO" },
  { prefijo: "3731", areaLocal: "CHARATA - CHACO" },
  { prefijo: "3734", areaLocal: "PRESIDENCIA DE LA PLAZA - CHACO" },
  { prefijo: "3735", areaLocal: "VILLA ANGELA - CHACO" },
  { prefijo: "3741", areaLocal: "BERNARDO DE IRIGOYEN - MISIONES" },
  { prefijo: "3743", areaLocal: "PUERTO RICO - MISIONES" },
  { prefijo: "3751", areaLocal: "ELDORADO - MISIONES" },
  { prefijo: "3754", areaLocal: "LEANDRO N. ALEM (PROV. MISIONES)" },
  { prefijo: "3755", areaLocal: "OBERA - MISIONES" },
  { prefijo: "3756", areaLocal: "SANTO TOME - CORRIENTES" },
  { prefijo: "3757", areaLocal: "PUERTO IGUAZU - MISIONES" },
  { prefijo: "3758", areaLocal: "APOSTOLES - MISIONES" },
  { prefijo: "3772", areaLocal: "PASO DE LOS LIBRES - CORRIENTES" },
  { prefijo: "3773", areaLocal: "MERCEDES (PROV. CORRIENTES)" },
  { prefijo: "3774", areaLocal: "CURUZU CUATIA - CORRIENTES" },
  { prefijo: "3775", areaLocal: "MONTE CASEROS - CORRIENTES" },
  { prefijo: "3777", areaLocal: "GOYA - CORRIENTES" },
  { prefijo: "3781", areaLocal: "CAA CATI - CORRIENTES" },
  { prefijo: "3782", areaLocal: "SALADAS - CORRIENTES" },
  { prefijo: "3786", areaLocal: "ITUZAINGO - CORRIENTES" },
  { prefijo: "3821", areaLocal: "CHEPES - LA RIOJA" },
  { prefijo: "3825", areaLocal: "CHILECITO - LA RIOJA" },
  { prefijo: "3826", areaLocal: "CHAMICAL - LA RIOJA" },
  { prefijo: "3827", areaLocal: "AIMOGASTA - LA RIOJA" },
  { prefijo: "3832", areaLocal: "RECREO (PROV. CATAMARCA)" },
  { prefijo: "3835", areaLocal: "ANDALGALA - CATAMARCA" },
  { prefijo: "3837", areaLocal: "TINOGASTA - CATAMARCA" },
  { prefijo: "3838", areaLocal: "SANTA MARIA (PROV. CATAMARCA)" },
  { prefijo: "3841", areaLocal: "MONTE QUEMADO - SANTIAGO DEL ESTERO" },
  { prefijo: "3843", areaLocal: "QUIMILI - SANTIAGO DEL ESTERO" },
  { prefijo: "3844", areaLocal: "ANATUYA - SANTIAGO DEL ESTERO" },
  { prefijo: "3845", areaLocal: "LORETO - SANTIAGO DEL ESTERO" },
  { prefijo: "3846", areaLocal: "TINTINA - SANTIAGO DEL ESTERO" },
  { prefijo: "3854", areaLocal: "FRIAS - SANTIAGO DEL ESTERO" },
  { prefijo: "3855", areaLocal: "SUNCHO CORRAL - SANTIAGO DEL ESTERO" },
  { prefijo: "3856", areaLocal: "OJO DE AGUA (PROV. SANTIAGO DEL ESTERO)" },
  { prefijo: "3857", areaLocal: "BANDERA - SANTIAGO DEL ESTERO" },
  { prefijo: "3858", areaLocal: "TERMAS DE RIO HONDO - SANTIAGO DEL ESTERO" },
  { prefijo: "3861", areaLocal: "NUEVA ESPERANZA - SANTIAGO DEL ESTERO" },
  { prefijo: "3862", areaLocal: "TRANCAS - TUCUMAN" },
  { prefijo: "3863", areaLocal: "MONTEROS - TUCUMAN" },
  { prefijo: "3865", areaLocal: "CONCEPCION (PROV. TUCUMAN)" },
  { prefijo: "3867", areaLocal: "TAFI DEL VALLE - TUCUMAN" },
  { prefijo: "3868", areaLocal: "CAFAYATE - SALTA" },
  { prefijo: "3869", areaLocal: "RANCHILLOS - TUCUMAN" },
  { prefijo: "3873", areaLocal: "TARTAGAL (PROV. SALTA)" },
  { prefijo: "3876", areaLocal: "METAN - SALTA" },
  { prefijo: "3877", areaLocal: "JOAQUIN V. GONZALEZ - SALTA" },
  { prefijo: "3878", areaLocal: "ORAN - SALTA" },
  { prefijo: "3885", areaLocal: "LA QUIACA - JUJUY" },
  { prefijo: "3886", areaLocal: "LIBERTADOR GENERAL SAN MARTIN - JUJUY" },
  { prefijo: "3887", areaLocal: "HUMAHUACA - JUJUY" },
  { prefijo: "3888", areaLocal: "SAN PEDRO (PROV. JUJUY)" },
  { prefijo: "3891", areaLocal: "LA MADRID - TUCUMAN" },
  { prefijo: "3892", areaLocal: "AMAICHA DEL VALLE - TUCUMAN" },
  { prefijo: "3894", areaLocal: "BURRUYACU - TUCUMAN" },
];

const PREFIJO_SET = new Set(ARGENTINA_PREFIJOS_CATALOGO.map((item) => item.prefijo));
const THREE_DIGIT_PREFIXES = new Set(
  ARGENTINA_PREFIJOS_CATALOGO.map((item) => item.prefijo).filter(
    (prefijo) => prefijo.length === 3,
  ),
);

function normalizeTelefono(value?: unknown) {
  let digits = String(value ?? "").replace(/\D/g, "");

  if (digits.startsWith("00")) {
    digits = digits.slice(2);
  }

  if (digits.startsWith("54")) {
    digits = digits.slice(2);
  }

  if (digits.startsWith("0") && digits.length > 10) {
    digits = digits.slice(1);
  }

  if (digits.startsWith("9") && digits.length > 10) {
    digits = digits.slice(1);
  }

  return digits;
}

export function extractPrefijoArgentina(value?: unknown) {
  const digits = normalizeTelefono(value);

  if (!digits) return "00";

  for (const len of [4, 3, 2]) {
    const candidate = digits.slice(0, len);
    if (PREFIJO_SET.has(candidate)) return candidate;
  }

  if (digits.startsWith("11")) return "11";

  const threeDigitCandidate = digits.slice(0, 3);
  if (THREE_DIGIT_PREFIXES.has(threeDigitCandidate)) {
    return threeDigitCandidate;
  }

  if (digits.length >= 10) return digits.slice(0, 4);
  if (digits.length >= 8) return digits.slice(0, 3);

  return digits.slice(0, 2) || "00";
}
